# Generated by Django 2.2.3 on 2019-07-20 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190719_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='creator',
            field=models.CharField(help_text='Enter the name of the creator', max_length=200),
        ),
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copied_at', models.DateTimeField(auto_now_add=True)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Snippet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-copied_at'],
            },
        ),
        migrations.AddField(
            model_name='snippet',
            name='copy_snippet',
            field=models.ManyToManyField(help_text='Click to add snippet to user page.', through='core.UserPage', to=settings.AUTH_USER_MODEL),
        ),
    ]
