# Generated by Django 2.2.3 on 2019-07-20 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190720_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='copy_snippet',
            field=models.ManyToManyField(help_text='Click to add snippet to user page.', related_name='LoggedIn', through='core.UserPage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='languages',
            field=models.CharField(choices=[('python', 'python'), ('js', 'js'), ('html', 'html'), ('lua', 'lua'), ('css', 'css'), ('clike', 'clike'), ('markup', 'markup'), ('html', 'html'), ('bash', 'bash'), ('django', 'django'), ('go', 'go'), ('json', 'json'), ('http', 'http'), ('php', 'php'), ('ruby', 'ruby'), ('sas', 'sas'), ('sass', 'sass'), ('scss', 'scss'), ('sql', 'sql')], default='html', max_length=7),
        ),
    ]
